# 맛집 위치를 지도에 표시하기

In [14]:
import folium
import pandas as pd
import googlemaps
import numpy as np
from tqdm import tqdm

In [5]:
df = pd.read_csv('03. best_sandwitches_list_chicago2.csv', index_col ='Rank')
df

,Name,Menu,price,address
Rank,,,,
1,BLT,Old Oak Tap,10,2109 W Chicago Ave
2,Fried Bologna,Au Cheval,9,800 W Randolph St
3,Woodland Mushroom,Xoco,9,50 445 N Clark St
4,Roast Beef,Al’s Deli,9,40 914 Noyes St
5,PB&L,Publican Quality Meats,10,825 W Fulton Mkt
6,Belgian Chicken Curry Salad,Hendrickx Belgian Bread Crafter,7,25 100 E Walton St
7,Lobster Roll,Acadia,16,1639 S Wabash Ave
8,Smoked Salmon Salad,Birchwood Kitchen,10,2211 W North Ave
9,Atomica Cemitas,Cemitas Puebla,9,3619 W North Ave
10,Grilled Laughing Bird Shrimp and Fried Po’ Boy,Nana,17,3267 S Halsted St
11,Ham and Raclette Panino,Lula Cafe,11,2537 N Kedzie Blvd
12,Breaded Steak,Ricobene’s,5,49 Multiple locations
13,The Hawkeye,Frog n Snail,14,3124 N Broadway
14,Chicken Dip,Crosby’s Kitchen,10,3455 N Southport Ave
15,Wild Boar Sloppy Joe,Longman & Eagle,13,2657 N Kedzie Ave
16,Meatball Sub,Bari,4,50 1120 W Grand Ave
17,Corned Beef,Manny’s,11,95 1141 S Jefferson St
18,Turkey Club,Eggy’s,11,50 333 E Benton Pl
19,Falafel,Old Jerusalem,6,25 1411 N Wells St
20,Crab Cake,Mindy’s HotChocolate,15,1747 N Damen Ave
21,Chicken Schnitzel,Olga’s Delicatessen,5,3209 W Irving Park Rd
22,Shawarma,Dawali Mediterranean Kitchen,6,Multiple locations
23,Toasted Pimiento Cheese,Big Jones,8,5347 N Clark St
24,Vegetarian Panino,La Pane,5,99 2954 W Irving Park Rd
25,Cali Chèvre,Pastoral,7,52 Multiple locations
26,Pastrami,Max’s Deli,11,95 191 Skokie Valley Rd
27,The Fredo,Lucky’s Sandwich Co.,7,50 Multiple locations
28,Smoked Ham,City Provisions,12,95 1818 W Wilson Ave
29,Jibarito,Papa’s Cache Sabroso,7,2517 W Division St
30,Shaved Prime Rib,Bavette’s Bar & Boeuf,21,218 W Kinzie St
31,Serrano Ham and Manchego Cheese,Hannah’s Bretzel,9,79 Multiple locations
32,Tuna Salad,La Fournette,9,75 1547 N Wells St
33,Paramount Reuben,Paramount Room,13,415 N Milwaukee Ave
34,The Istanbul,Melt Sandwich Shoppe,7,95 1840 N Damen Ave
35,B.A.D.,Floriole Cafe & Bakery,9,1220 W Webster Ave
36,Duck Confit and Mozzarella,First Slice Pie Café,9,5357 N Ashland Ave
37,Croque Monsieur,Troquet,8,1834 W Montrose Ave
38,Green Garbanzo,Grahamwich,8,615 N State St
39,The Hen House,Saigon Sisters,7,Multiple locations
40,Tuscan Chicken,Rosalia’s Deli,6,241 N York Rd
41,The Marty,Z&H MarketCafe,7,25 1323 E 57th St
42,Whitefish,Market House on the Square,11,655 Forest Ave
43,"Oat Bread, Pecan Butter, and Fruit Jam",Elaine’s Coffee Call,6,Hotel Lincoln
44,Cauliflower Melt,Marion Street Cheese Market,9,100 S Marion St
45,Cubana,Cafecito,5,49 26 E Congress Pkwy
46,Kufta,Chickpea,8,2018 W Chicago Ave
47,Debbie’s Egg Salad,The Goddess and Grocer,6,50 25 E Delaware Pl
48,Beef Curry,Zenwich,7,50 416 N York St
49,Le Végétarien,Toni Patisserie,8,75 65 E Washington St
50,The Gatsby,Phoebe’s Bakery,6,85 3351 N Broadway

In [4]:
gmaps_key = 'AIzaSyDNK_5FJCc6n3PI_A5LoTxt4xKA2Fd935M'
gmaps = googlemaps.Client(key = gmaps_key)

In [13]:
geo = gmaps.geocode('Delaware', language = 'en')
geo[0].get('geometry')

{'bounds': {'northeast': {'lat': 39.8394839, 'lng': -74.98416499999999},
  'southwest': {'lat': 38.451018, 'lng': -75.78914790000002}},
 'location': {'lat': 38.9108325, 'lng': -75.52766989999999},
 'location_type': 'APPROXIMATE',
 'viewport': {'northeast': {'lat': 39.8394839, 'lng': -74.98416499999999},
  'southwest': {'lat': 38.451018, 'lng': -75.78914790000002}}}

In [19]:
lat = []
lng = []

for address in tqdm(df['address']):
    if 'Multiple' not in address:
        target_name = address + ', Chicago'
        gmaps_geocode = gmaps.geocode(target_name, language='en')
        
        location_output = gmaps_geocode[0].get('geometry')
        lat.append(location_output['location']['lat'])
        lng.append(location_output['location']['lng'])
    
    else:
        lat.append(np.nan)
        lng.append(np.nan)

100%|██████████████████████████████████████████████████████████████████████████████████| 50/50 [00:10<00:00,  4.80it/s]

In [22]:
lat, lng

([41.8956049,
  41.8846582,
  41.8905226,
  42.0589141,
  41.8866036,
  41.9002461,
  41.8590541,
  41.9102031,
  41.9097558,
  41.8345302,
  41.9276207,
  nan,
  41.9384419,
  41.9451044,
  41.9301107,
  41.89129000000001,
  41.8678529,
  41.8852691,
  41.9080539,
  41.91369539999999,
  41.9537106,
  nan,
  41.9794496,
  41.9541563,
  nan,
  42.1567073,
  nan,
  41.9652987,
  41.90272179999999,
  41.8893683,
  nan,
  41.9105258,
  41.8896188,
  41.91504990000001,
  41.9218521,
  41.9797099,
  41.9617122,
  41.89296119999999,
  nan,
  41.9047551,
  41.7913185,
  41.7068231,
  41.9152875,
  41.8863622,
  41.8758102,
  41.8960738,
  41.89897850000001,
  41.9105832,
  41.8831061,
  41.9431632],
 [-87.67996149999999,
  -87.6476668,
  -87.6307834,
  -87.9940852,
  -87.64853649999999,
  -87.62516339999999,
  -87.6252007,
  -87.68287529999999,
  -87.7176727,
  -87.6456492,
  -87.706792,
  nan,
  -87.64464369999999,
  -87.6636812,
  -87.7072408,
  -87.655557,
  -87.6419289,
  -87.6184837,
  -87.6343113,
  -87.6771273,
  -87.7084504,
  nan,
  -87.66795719999999,
  -87.7027107,
  nan,
  -87.8036345,
  nan,
  -87.67557959999999,
  -87.6902135,
  -87.6349487,
  nan,
  -87.6343775,
  -87.64484259999999,
  -87.6778047,
  -87.6592124,
  -87.66934409999999,
  -87.67581620000001,
  -87.6278214,
  nan,
  -87.9396459,
  -87.5938456,
  -87.61618650000001,
  -87.6343888,
  -87.8022297,
  -87.6264489,
  -87.6778185,
  -87.6273926,
  -87.94048839999999,
  -87.6254381,
  -87.6445071])

- Pandas의 df['열이름'].mean() 메소드를 사용하기 위해. 자동적으로 nan값을 제외하고 return한다

In [41]:
df['lat'] = lat
df['lng'] = lng
df.head(15)

,Name,Menu,price,address,lat,lng
Rank,,,,,,
1,BLT,Old Oak Tap,10,2109 W Chicago Ave,41.895605,-87.679961
2,Fried Bologna,Au Cheval,9,800 W Randolph St,41.884658,-87.647667
3,Woodland Mushroom,Xoco,9,50 445 N Clark St,41.890523,-87.630783
4,Roast Beef,Al’s Deli,9,40 914 Noyes St,42.058914,-87.994085
5,PB&L,Publican Quality Meats,10,825 W Fulton Mkt,41.886604,-87.648536
6,Belgian Chicken Curry Salad,Hendrickx Belgian Bread Crafter,7,25 100 E Walton St,41.900246,-87.625163
7,Lobster Roll,Acadia,16,1639 S Wabash Ave,41.859054,-87.625201
8,Smoked Salmon Salad,Birchwood Kitchen,10,2211 W North Ave,41.910203,-87.682875
9,Atomica Cemitas,Cemitas Puebla,9,3619 W North Ave,41.909756,-87.717673
10,Grilled Laughing Bird Shrimp and Fried Po’ Boy,Nana,17,3267 S Halsted St,41.834530,-87.645649
11,Ham and Raclette Panino,Lula Cafe,11,2537 N Kedzie Blvd,41.927621,-87.706792
12,Breaded Steak,Ricobene’s,5,49 Multiple locations,NaN,NaN
13,The Hawkeye,Frog n Snail,14,3124 N Broadway,41.938442,-87.644644
14,Chicken Dip,Crosby’s Kitchen,10,3455 N Southport Ave,41.945104,-87.663681
15,Wild Boar Sloppy Joe,Longman & Eagle,13,2657 N Kedzie Ave,41.930111,-87.707241

In [40]:
''' 50개 위치의 평균값 두기 '''
mapping = folium.Map([df['lat'].mean(), df['lng'].mean()], zoom_start = 11)

folium.Marker([df['lat'].mean(), df['lng'].mean()], popup = 'center').add_to(mapping)

mapping

In [53]:
mapping = folium.Map( [df['lat'].mean(), df['lng'].mean()] , zoom_start = 11)

for place in df['address']:
    if 'Multiple' not in place:
        folium.Marker( location = [ df['lat'][place], df['lng'][place] ] ,    
                      # 인덱싱에 문제가 있는 듯
                     popup = df['Name'][place] ).add_to(mapping)
mapping

KeyError: ' 2109 W Chicago Ave'